{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      " INFORMATION\n",
      "\n",
      "Dataset: unsw_nb15\n",
      "Total number of instances: 79924\n",
      "Number Training Cases: 55947\n",
      "Number Validation Cases: 7992\n",
      "Number Testing Cases: 15985\n",
      "\n",
      "Run:1\n",
      "Criteria: gini     Ens method: SV\n",
      "Running...\n",
      "numTrees: 1\n",
      "Training finished\n",
      "Fitness:  96.15264310290897\n",
      "numTrees: 3\n",
      "Training finished\n",
      "Fitness:  96.95964967156709\n",
      "numTrees: 5\n",
      "Training finished\n",
      "Fitness:  97.11604629340006\n",
      "numTrees: 7\n",
      "Training finished\n",
      "Fitness:  97.3913043478261\n",
      "numTrees: 9\n",
      "Training finished\n",
      "Fitness:  97.38504848295277\n",
      "numTrees: 11\n",
      "Training finished\n",
      "Fitness:  97.49139818579918\n",
      "numTrees: 13\n",
      "Training finished\n",
      "Fitness:  97.51016578041914\n",
      "numTrees: 15\n",
      "Training finished\n",
      "Fitness:  97.51642164529247\n",
      "numTrees: 17\n",
      "Training finished\n",
      "Fitness:  97.51642164529247\n",
      "numTrees: 19\n",
      "Training finished\n",
      "Fitness:  97.54144510478574\n",
      "numTrees: 21\n",
      "Training finished\n",
      "Fitness:  97.5602126994057\n",
      "numTrees: 23\n",
      "Training finished\n",
      "Fitness:  97.67907413199875\n",
      "numTrees: 25\n",
      "Training finished\n",
      "Fitness:  97.52267751016578\n",
      "numTrees: 27\n",
      "Training finished\n",
      "Fitness:  97.6290272130122\n",
      "numTrees: 29\n",
      "training 1%\r"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/sy/n7rh139x6tl49pn2wm46j4vd7tmz20/T/ipykernel_20415/3635675030.py\", line 116, in <module>\n",
      "    algorithms[-1].fit(dataTraining, targetTraining, percentage)\n",
      "  File \"/Users/tmc01/DataspellProjects/paper3/for git/RandomForest.py\", line 57, in fit\n",
      "    self.trees[i].fit(Data[indexes,:], target[indexes])\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n",
      "    super().fit(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py\", line 458, in fit\n",
      "    builder.build(self.tree_, X, y, sample_weight)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 1503, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 182, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/linecache.py\", line 46, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/linecache.py\", line 136, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/tokenize.py\", line 392, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/sy/n7rh139x6tl49pn2wm46j4vd7tmz20/T/ipykernel_20415/3635675030.py\", line 116, in <module>\n",
      "    algorithms[-1].fit(dataTraining, targetTraining, percentage)\n",
      "  File \"/Users/tmc01/DataspellProjects/paper3/for git/RandomForest.py\", line 57, in fit\n",
      "    self.trees[i].fit(Data[indexes,:], target[indexes])\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n",
      "    super().fit(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py\", line 458, in fit\n",
      "    builder.build(self.tree_, X, y, sample_weight)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2066, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 752, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 721, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 706, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/sy/n7rh139x6tl49pn2wm46j4vd7tmz20/T/ipykernel_20415/3635675030.py\", line 116, in <module>\n",
      "    algorithms[-1].fit(dataTraining, targetTraining, percentage)\n",
      "  File \"/Users/tmc01/DataspellProjects/paper3/for git/RandomForest.py\", line 57, in fit\n",
      "    self.trees[i].fit(Data[indexes,:], target[indexes])\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py\", line 969, in fit\n",
      "    super().fit(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py\", line 458, in fit\n",
      "    builder.build(self.tree_, X, y, sample_weight)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2066, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2066, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 1541, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 1499, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 709, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/inspect.py\", line 755, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/posixpath.py\", line 392, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/posixpath.py\", line 426, in _joinrealpath\n",
      "    if not islink(newpath):\n",
      "  File \"/Users/tmc01/opt/anaconda3/lib/python3.9/posixpath.py\", line 167, in islink\n",
      "    st = os.lstat(path)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "from sklearn.datasets import load_iris\n",
    "import RandomForest as RF\n",
    "import os.path\n",
    "import os\n",
    "from datetime import datetime\n",
    "import bz2\n",
    "import _pickle as cPickle\n",
    "import numpy as np\n",
    "import random\n",
    "\n",
    "\n",
    "my_os = \"mac\" #win mac\n",
    "\n",
    "separator = \"\\\\\"\n",
    "\n",
    "if my_os == \"mac\":\n",
    "    separator = \"//\"\n",
    "\n",
    "today = datetime.now()\n",
    "# folderName = folderName = 'Experiments 1 '  + today.strftime(\"%d-%b-%Y %H_%M_%S\")\n",
    "\n",
    "folderName = 'Experiments 1'\n",
    "\n",
    "if not os.path.exists(folderName):\n",
    "    os.makedirs(folderName)\n",
    "\n",
    "no_runs = 5\n",
    "\n",
    "dataset = \"unsw_nb15\" # iris kdd  nsl_kdd  unsw_nb15 cic_ids_2017\n",
    "problem = \"AD\" # AD AC\n",
    "TrainingPercentage = 0.7\n",
    "ValidationPercentage = 0.1\n",
    "TestingPercentage = 0.2\n",
    "\n",
    "if dataset == \"iris\":\n",
    "    iris = load_iris()\n",
    "    data, target = iris.data, iris.target\n",
    "\n",
    "if dataset == \"kdd\":\n",
    "    file_name = \"data\" + separator + \"kdd_subsets.pbz2\"\n",
    "    f = bz2.BZ2File(file_name, \"rb\")\n",
    "    data, target, subsets = cPickle.load(f)\n",
    "    f.close()\n",
    "    label_for_normal = 3\n",
    "\n",
    "if dataset == \"nsl_kdd\":\n",
    "    file_name = \"data\" + separator +  \"nsl_kdd_subsets.pbz2\"\n",
    "    f = bz2.BZ2File(file_name, \"rb\")\n",
    "    data, target, subsets = cPickle.load(f)\n",
    "    f.close()\n",
    "    label_for_normal = 4\n",
    "\n",
    "if dataset == \"unsw_nb15\":\n",
    "    file_name = \"data\" + separator + \"unsw_nb15_subsets.pbz2\"\n",
    "    f = bz2.BZ2File(file_name, \"rb\")\n",
    "    data, target, subsets = cPickle.load(f)\n",
    "    f.close()\n",
    "    label_for_normal = 4\n",
    "\n",
    "if dataset == \"cic_ids_2017\":\n",
    "    file_name = \"data\" + separator +  \"cic_ids_2017_subsets.pbz2\"\n",
    "    f = bz2.BZ2File(file_name, \"rb\")\n",
    "    data, target, subsets = cPickle.load(f)\n",
    "    f.close()\n",
    "    label_for_normal = 0\n",
    "\n",
    "if problem == \"AD\" and dataset != \"iris\":\n",
    "    target[target != label_for_normal] = 1\n",
    "    target[target == label_for_normal] = 0\n",
    "\n",
    "num_classes = np.unique(target).shape[0]\n",
    "\n",
    "# Dividing the dataset\n",
    "total_number_instances = len(data)\n",
    "indexes = range(len(data))\n",
    "indexes = random.sample(indexes, round(TrainingPercentage * total_number_instances))\n",
    "dataTraining = data[indexes,:]\n",
    "targetTraining = target[indexes]\n",
    "data = np.delete(data, indexes, axis = 0)\n",
    "target = np.delete(target, indexes, axis = 0)\n",
    "indexes = range(len(data))\n",
    "indexes = random.sample(indexes, round(ValidationPercentage * total_number_instances))\n",
    "dataValidation = data[indexes,:]\n",
    "targetValidation = target[indexes]\n",
    "dataTesting = np.delete(data, indexes, axis = 0)\n",
    "targetTesting = np.delete(target, indexes, axis = 0)\n",
    "\n",
    "print(\"\\n INFORMATION\\n\")\n",
    "print(\"Dataset: \"+dataset)\n",
    "print(\"Total number of instances: \"+str(total_number_instances))\n",
    "print(\"Number Training Cases: \"+str(dataTraining.shape[0]))\n",
    "print(\"Number Validation Cases: \"+str(dataValidation.shape[0]))\n",
    "print(\"Number Testing Cases: \"+str(dataTesting.shape[0])+\"\\n\")\n",
    "\n",
    "\n",
    "percentage = 0.7\n",
    "criterions = [\"gini\", \"entropy\"]\n",
    "ensemble_methods = [\"SV\", \"WV\"] # SV   WV\n",
    "\n",
    "for i in range(1,no_runs+1):\n",
    "    print(\"Run:\" + str(i))\n",
    "    for em in range(len(ensemble_methods)):\n",
    "        ensemble_method = ensemble_methods[em]\n",
    "        for cr in range(len(criterions)):\n",
    "            criterion_input = criterions[cr]\n",
    "            print(\"Criteria: \"+criterion_input+\"     Ens method: \"+ensemble_method)\n",
    "            file_name = folderName+separator+\"RF_\"+dataset+\"_\"+problem+\"_\"+criterion_input+\"_\"+ensemble_method+\"_\"+str(i)+\".pbz2\"\n",
    "            if not os.path.exists(file_name):\n",
    "                print(\"Running...\")\n",
    "                algorithms = []\n",
    "                for num_trees in range(100):\n",
    "\n",
    "                    if num_trees % 2 == 1:\n",
    "                        print(\"numTrees: \"+str(num_trees))\n",
    "                        algorithms.append(RF.RandomForest(num_trees, criterion_input, ensemble_method, num_classes))\n",
    "                        algorithms[-1].fit(dataTraining, targetTraining, percentage)\n",
    "                        algorithms[-1].validate(dataValidation, targetValidation)\n",
    "                        algorithms[-1].predict(dataTesting, targetTesting)\n",
    "                        print(\"Fitness: \",str(algorithms[-1].statisticsRF.accuracy))\n",
    "\n",
    "                f = bz2.BZ2File(file_name, \"wb\")\n",
    "                cPickle.dump((algorithms),f)\n",
    "                f.close()\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n",
     "is_executing": true
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}